name: release
on:
  push:
    branches:
      - master
jobs:
  release-please:
    name: release-please
    runs-on: ubuntu-latest
    outputs:
      release-prisma: ${{ steps.release.outputs['packages/prisma--release_created'] }}
      release-storage: ${{ steps.release.outputs['packages/storage--release_created'] }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: release
        uses: googleapis/release-please-action@v4
  release-packages:
    name: release-packages
    runs-on: ubuntu-latest
    needs:
      - release-please
    strategy:
      matrix:
        package:
          - name: "@joshuaavalon/fastify-plugin-prisma"
            is-release: ${{ needs.release-please.outputs.release-prisma }}
          - name: "@joshuaavalon/fastify-plugin-storage"
            is-release: ${{ needs.release-please.outputs.release-storage }}
    steps:
      - uses: ./.github/workflows/publish.yml
        with:
          package-name: ${{ matrix.package.name }}
          is-release: ${{ matrix.package.is-release }}
