name: release
on:
  push:
    branches:
      - master
jobs:
  release-please:
    name: release-please
    runs-on: ubuntu-latest
    outputs:
      release-prisma: ${{ steps.release.outputs['packages/prisma--release_created'] || false }}
      release-storage: ${{ steps.release.outputs['packages/storage--release_created'] || false }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: release
        uses: googleapis/release-please-action@v4
  release-packages:
    name: release-packages
    needs:
      - release-please
    permissions:
      id-token: write
    strategy:
      matrix:
        package:
          - name: "@joshuaavalon/fastify-plugin-prisma"
            is-release: ${{ fromJSON(needs.release-please.outputs.release-prisma) }}
          - name: "@joshuaavalon/fastify-plugin-storage"
            is-release: ${{ fromJSON(needs.release-please.outputs.release-storage) }}
    uses: ./.github/workflows/publish.yml
    with:
      package-name: ${{ matrix.package.name }}
      is-release: ${{ matrix.package.is-release }}
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
