name: release
on:
  push:
    branches:
      - master
jobs:
  release-please:
    name: release-please
    runs-on: ubuntu-latest
    outputs:
      release-prisma: ${{ steps.release.outputs['packages/prisma--release_created'] || false }}
      release-storage: ${{ steps.release.outputs['packages/storage--release_created'] || false }}
      release-typebox: ${{ steps.release.outputs['packages/typebox--release_created'] || false }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: release
        uses: googleapis/release-please-action@v4
  release-packages:
    name: release-packages
    runs-on: ubuntu-latest
    needs:
      - release-please
    strategy:
      matrix:
        package:
          - name: "@joshuaavalon/fastify-plugin-prisma"
            is-release: ${{ fromJSON(needs.release-please.outputs.release-prisma) }}
          - name: "@joshuaavalon/fastify-plugin-storage"
            is-release: ${{ fromJSON(needs.release-please.outputs.release-storage) }}
          - name: "@joshuaavalon/fastify-plugin-typebox"
            is-release: ${{ fromJSON(needs.release-please.outputs.release-typebox) }}
        exclude:
          - package:
              is-release: false
    permissions:
      id-token: write
    steps:
      - if: ${{ matrix.package.is-release }}
        uses: joshuaavalon/publish-npm@v1
        with:
          workspace: ${{ matrix.package.name }}
          npm-token: ${{ secrets.NPM_TOKEN }}
